version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: password_generator_backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: password_generator_frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./frontend:/app
